---
title: "Interactive NBA Timeline App"
author: "Shevya Panda, etc"
date: "11/27/2024"
output: html_document
---

```{r}
library(tidyverse)
library(shiny)
NBA<-read.csv("DS2003_NBA_Data.csv")
head(NBA)
```

```{r}
ggplot(NBA[NBA$Player=="LeBron James", ], aes(x=GameDay, y=PTS, group=1)) + geom_line()
```

***Data Wrangling***

```{r}
NBA$Season <- ifelse(month(NBA$GameDay) %in% c(10, 11, 12, 1, 2, 3, 4), 
                         year(NBA$GameDay), 
                         year(NBA$GameDay) - 1) 
#this part calculates the previous and following year to make sure the graph stays in numerical order, I found from a quick google search that the NBA season is from October to April of the following year.

NBA1 <- NBA %>%
  group_by(Player, Season) %>%
  summarise(
    Avg_PTS = mean(PTS),
    Avg_AST = mean(AST),
    Avg_REB = mean(REB),
    Avg_STL = mean(STL),
    Avg_BLK = mean(BLK)
  )

head(NBA1)
```

***Initial Graph Filtering LeBron Data***

```{r}
ggplot(NBA1 %>% filter(Player == "LeBron James"), 
       aes(x = Season, y = Avg_PTS)) + 
  geom_line() + 
  geom_point() + 
  labs(x = "Season", y = "Average Points") + 
  theme(axis.text.x = element_text(angle = 90))
```

***App Creation***

```{r}
ggplot(NBA1 %>% filter(Player == "LeBron James"), 
       aes(x = Season, y = Avg_PTS)) + 
  geom_line() + 
  geom_point() + 
  labs(x = "Season", y = "Average Points", title = "Average - Per Season") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + 
  scale_x_continuous(breaks = NBA1$Season %>% unique()) + 
  scale_y_continuous(limits = c(0, max(NBA1$Avg_PTS)))
```

In the panel above I looked up how to make the dates at a 90 degree angle so onlookers can see each one clearly, and then I make it so that the points all starts from 0 so viewers can see how different players differ when looking at the app more clearly. I'm having trouble doing that to the x axis

```{r}
library(shiny)
library(shinythemes)
library(ggplot2)

ui <- fluidPage(
  theme = shinytheme("superhero"),
  titlePanel("NBA Player Average Statistics"),
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "player", 
                    label = "Select Player:", 
                    choices = unique(NBA1$Player)),
      selectInput(inputId = "stat", 
                    label = "Select Statistic:", 
                    choices = c("Avg_PTS", "Avg_BLK", "Avg_AST", "Avg_REB", "Avg_STL"))
    ),
    mainPanel(
      plotOutput("player_graph")
    )
  )
)

server <- function(input, output) {
  output$player_graph <- renderPlot({
    player_data <- NBA1 %>% 
      filter(Player == input$player)
    
    ggplot(player_data, aes(x = Season, y = !!sym(input$stat))) + 
      geom_line(color = "blue") + 
      geom_point() + 
      labs(x = "Season", y = input$stat, title = "Average NBA Player Statistics") + 
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + 
      scale_y_continuous(limits = c(0, max(player_data[, input$stat])))
  })
}

shinyApp(ui, server)
```
